title: "Ashutosh Mahajan"
theme: jekyll-theme-minimal
description: "Ashutosh Mahajan's GitHub Portfolio - VR Developer, Game Programmer"
paginate: 5  # Limit number of blog posts shown per page if applicable
